db:
  image: postgres
  volumes:
    - /opt/registry-storage/database:/var/lib/postgresql

uwsgi:
  restart: always
  build: .
  #image: quay.io/vanessa/sregistry
  volumes:
    - .:/code
    - ./static:/var/www/static
    - /opt/registry-storage/images:/var/www/images
    # uncomment for PAM auth
    #- /etc/passwd:/etc/passwd 
    #- /etc/shadow:/etc/shadow
  links:
    - redis
    - db

nginx:
  restart: always
  image: quay.io/vanessa/sregistry_nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
    - /etc/ssl/certs:/etc/ssl/certs:ro
    - /etc/ssl/private:/etc/ssl/private:ro
  volumes_from:
    - uwsgi
  links:
    - uwsgi
    - db

redis:
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"

scheduler:
  build: .
  #image: quay.io/vanessa/sregistry
  command: python /code/manage.py rqscheduler
  volumes:
    - .:/code
  volumes_from:
    - uwsgi
  links:
    - redis
    - db

worker:
  build: .
  #image: quay.io/vanessa/sregistry
  command: python /code/manage.py rqworker default
  volumes:
    - .:/code
  volumes_from:
    - uwsgi
  links:
    - redis
    - db
