db:
  image: postgres
 
uwsgi:
  restart: always
  image: quay.io/vanessa/sregistry
  volumes:
    - .:/code
    - ./static:/var/www/static
    - /opt/registry-storage/:/var/www/images
    # uncomment for PAM auth
    #- /etc/passwd:/etc/passwd 
    #- /etc/shadow:/etc/shadow
  links:
    - redis
    - db

nginx:
  restart: always
  image: quay.io/vanessa/sregistry_nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
  volumes_from:
    - uwsgi
  links:
    - uwsgi
    - db

redis:
  restart: always
  image: redis:latest

scheduler:
  image: quay.io/vanessa/sregistry
  command: python /code/manage.py rqscheduler
  volumes:
    - .:/code
  volumes_from:
    - uwsgi
  links:
    - redis
    - db

worker:
  image: quay.io/vanessa/sregistry
  command: python /code/manage.py rqworker default
  volumes:
    - .:/code
  volumes_from:
    - uwsgi
  links:
    - redis
    - db
